name: Trigger auto deployment for hello

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/hello-AutoDeployTrigger-6952818c-24b6-4b42-b73e-7f5ee60fc040.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: akubicharm.azurecr.io
          username: ${{ secrets.HELLO_REGISTRY_USERNAME }}
          password: ${{ secrets.HELLO_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: akubicharm.azurecr.io/hello:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.HELLO_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n hello -g aca --server akubicharm.azurecr.io --username  ${{ secrets.HELLO_REGISTRY_USERNAME }} --password ${{ secrets.HELLO_REGISTRY_PASSWORD }}
            az containerapp update -n hello -g aca --image akubicharm.azurecr.io/hello:${{ github.sha }}
